<?php
/**
*Implements hook_form_alter()
**/
function islandora_mods_on_ingest_form_alter(&$form, &$form_state, $form_id)
{
if ($form_id != 'xml_form_builder_ingest_form')
{
return;
}
$form['Image']=array(
'#title'=>t('Title'),
'#type'=>'textfield',
'#description'=> t('Please Enter Your Name')
);
$form['upload']=array(
'#type'=>'file',
'#description'=>t('Upload the Image'),
);
$form['submit']=array(
'#type'=>'submit',
'#value'=>('Submit')
);
return $form;
}

function islandora_mods_on_ingest_form_islandora_ingest_form_alter($form, &$form_state){
  if ($form_state['islandora']['step_id'] == 'islandora_basic_collection_select_content_model') {
    $form_state['islandora']['step_storage']['islandoa_mods_on_ingest_form'] = array(
      'weight' => -40,
      'type' => 'form',
      'form_id' => 'islandoa_mods_on_ingest_form',
      'module' => 'islandora_mods_on_ingest',
      'file' => 'includes/islandora_mods_on_ingest.form.inc',
    );
  }
}
