<?php

/**
 * @file
 * Main module file for Islandora MODS on Ingest.
 */

/**
 * Implements hook_form_form_alter().
 */
function islandora_mods_on_ingest_form_islandora_ingest_form_alter(&$form, &$form_state) {
  module_load_include('inc', 'islandora', 'includes/ingest.form');
  if($form_state['islandora']['step_id'] == 'islandora_basic_collection_select_content_model') {
    $upload_size = file_upload_max_size();
    $form['choose'] = array(
      '#type' => 'select',
      '#options' => array('Upload MODS?','Edit MODS using form'),
      '#default' => 0,
      '#weight' => -20,
    );
    $form['upload_file'] = array(
      '#weight' => -19,
      'dsid_fieldset' => array(
        //add visibility condition.
        '#states' => array(
          'visible' => array(
            ':input[name="choose"]' => array('value' => '0'),
          ),
        ),
        //borrow from datastream.inc
        '#type' => 'fieldset',
        '#title' => t("Upload MODS.xml"),
        '#collapsible' => FALSE,
        '#collapsed' => FALSE,
        'file' => array(
          '#type' => 'managed_file',
          '#required' => FALSE,
          '#title' => t('Upload Document'),
          '#size' => 64,
          '#description' => t('Select a file to upload.<br/>Files must be less than <strong>@size MB.</strong>', array('@size' => ($upload_size)/(1024*1024))),
          '#default_value' => isset($form_state['values']['files']) ? $form_state['values']['files'] : NULL,
          '#upload_location' => file_default_scheme() . '://',
          '#upload_validators' => array(
            'file_validate_extensions' => array('xml'),
            'file_validate_size' => array($upload_size),
          ),
        ),
      ),
    );
    array_unshift($form['next']['#submit'], 'mods_upload_submit');
    return $form;
  }
}

function mods_upload_submit($form, &$form_state) {
  module_load_include('inc', 'islandora', 'includes/ingest.form');
  if ($form_state['values']['choose'] == 0) {
    //borrowed from islandora_sp_large_image_cmodel and adapted for mods.
    //fills in the edit form at the next step, but we still have that edit step
    $object = islandora_ingest_form_get_object($form_state);
    if ($form_state['values']['file']) {
      $ds = $object->constructDatastream('MODS', 'M');
      $object->ingestDatastream($ds);
      $file = file_load($form_state['values']['file']);
      $path = drupal_realpath($file->uri);
      $ds->setContentFromFile($path, FALSE);
      $ds->label = $file->filename;
      $ds->mimetype = $file->filemime;
    }
  }
}
